# Generated by Django 4.2.4 on 2024-03-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocateregistration',
            name='exp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advocateregistration',
            name='qualification',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
