# Generated by Django 4.2.4 on 2024-03-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenapp', '0002_advocateregistration_exp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
