# Generated by Django 4.2.4 on 2024-03-06 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('womenapp', '0004_peoplerights_desc_peoplerights_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocateregistration',
            name='rights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='womenapp.peoplerights'),
        ),
    ]
