# Generated by Django 4.2.4 on 2024-03-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('womenapp', '0005_advocateregistration_rights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateregistration',
            name='lawyertype',
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='womenapp.advocateregistration')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='womenapp.userregistration')),
            ],
        ),
    ]
