# Generated by Django 4.2.4 on 2024-03-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenapp', '0007_petition_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
